#include "Vertex.h"
#include <array>

namespace lre::Vertex {
	std::unordered_map<uint64_t, vertexarray_function> MAP = {
		{ 0, NullVertex::VertexArray },
		{ position_flag, P1::VertexArray },
		{ color_flag, C1::VertexArray },
		{ position_flag | color_flag, P1C1::VertexArray },
		{ normal_flag, N1::VertexArray },
		{ position_flag | normal_flag, P1N1::VertexArray },
		{ color_flag | normal_flag, C1N1::VertexArray },
		{ position_flag | color_flag | normal_flag, P1C1N1::VertexArray },
		{ uv_flag, UV1::VertexArray },
		{ position_flag | uv_flag, P1UV1::VertexArray },
		{ color_flag | uv_flag, C1UV1::VertexArray },
		{ position_flag | color_flag | uv_flag, P1C1UV1::VertexArray },
		{ normal_flag | uv_flag, N1UV1::VertexArray },
		{ position_flag | normal_flag | uv_flag, P1N1UV1::VertexArray },
		{ color_flag | normal_flag | uv_flag, C1N1UV1::VertexArray },
		{ position_flag | color_flag | normal_flag | uv_flag, P1C1N1UV1::VertexArray },
		{ uvw_flag, UVW1::VertexArray },
		{ position_flag | uvw_flag, P1UVW1::VertexArray },
		{ color_flag | uvw_flag, C1UVW1::VertexArray },
		{ position_flag | color_flag | uvw_flag, P1C1UVW1::VertexArray },
		{ normal_flag | uvw_flag, N1UVW1::VertexArray },
		{ position_flag | normal_flag | uvw_flag, P1N1UVW1::VertexArray },
		{ color_flag | normal_flag | uvw_flag, C1N1UVW1::VertexArray },
		{ position_flag | color_flag | normal_flag | uvw_flag, P1C1N1UVW1::VertexArray },
		{ uv_flag | uvw_flag, UV1UVW1::VertexArray },
		{ position_flag | uv_flag | uvw_flag, P1UV1UVW1::VertexArray },
		{ color_flag | uv_flag | uvw_flag, C1UV1UVW1::VertexArray },
		{ position_flag | color_flag | uv_flag | uvw_flag, P1C1UV1UVW1::VertexArray },
		{ normal_flag | uv_flag | uvw_flag, N1UV1UVW1::VertexArray },
		{ position_flag | normal_flag | uv_flag | uvw_flag, P1N1UV1UVW1::VertexArray },
		{ color_flag | normal_flag | uv_flag | uvw_flag, C1N1UV1UVW1::VertexArray },
		{ position_flag | color_flag | normal_flag | uv_flag | uvw_flag, P1C1N1UV1UVW1::VertexArray },
		{ tex_flag, T1::VertexArray },
		{ position_flag | tex_flag, P1T1::VertexArray },
		{ color_flag | tex_flag, C1T1::VertexArray },
		{ position_flag | color_flag | tex_flag, P1C1T1::VertexArray },
		{ normal_flag | tex_flag, N1T1::VertexArray },
		{ position_flag | normal_flag | tex_flag, P1N1T1::VertexArray },
		{ color_flag | normal_flag | tex_flag, C1N1T1::VertexArray },
		{ position_flag | color_flag | normal_flag | tex_flag, P1C1N1T1::VertexArray },
		{ uv_flag | tex_flag, UV1T1::VertexArray },
		{ position_flag | uv_flag | tex_flag, P1UV1T1::VertexArray },
		{ color_flag | uv_flag | tex_flag, C1UV1T1::VertexArray },
		{ position_flag | color_flag | uv_flag | tex_flag, P1C1UV1T1::VertexArray },
		{ normal_flag | uv_flag | tex_flag, N1UV1T1::VertexArray },
		{ position_flag | normal_flag | uv_flag | tex_flag, P1N1UV1T1::VertexArray },
		{ color_flag | normal_flag | uv_flag | tex_flag, C1N1UV1T1::VertexArray },
		{ position_flag | color_flag | normal_flag | uv_flag | tex_flag, P1C1N1UV1T1::VertexArray },
		{ uvw_flag | tex_flag, UVW1T1::VertexArray },
		{ position_flag | uvw_flag | tex_flag, P1UVW1T1::VertexArray },
		{ color_flag | uvw_flag | tex_flag, C1UVW1T1::VertexArray },
		{ position_flag | color_flag | uvw_flag | tex_flag, P1C1UVW1T1::VertexArray },
		{ normal_flag | uvw_flag | tex_flag, N1UVW1T1::VertexArray },
		{ position_flag | normal_flag | uvw_flag | tex_flag, P1N1UVW1T1::VertexArray },
		{ color_flag | normal_flag | uvw_flag | tex_flag, C1N1UVW1T1::VertexArray },
		{ position_flag | color_flag | normal_flag | uvw_flag | tex_flag, P1C1N1UVW1T1::VertexArray },
		{ uv_flag | uvw_flag | tex_flag, UV1UVW1T1::VertexArray },
		{ position_flag | uv_flag | uvw_flag | tex_flag, P1UV1UVW1T1::VertexArray },
		{ color_flag | uv_flag | uvw_flag | tex_flag, C1UV1UVW1T1::VertexArray },
		{ position_flag | color_flag | uv_flag | uvw_flag | tex_flag, P1C1UV1UVW1T1::VertexArray },
		{ normal_flag | uv_flag | uvw_flag | tex_flag, N1UV1UVW1T1::VertexArray },
		{ position_flag | normal_flag | uv_flag | uvw_flag | tex_flag, P1N1UV1UVW1T1::VertexArray },
		{ color_flag | normal_flag | uv_flag | uvw_flag | tex_flag, C1N1UV1UVW1T1::VertexArray },
		{ position_flag | color_flag | normal_flag | uv_flag | uvw_flag | tex_flag, P1C1N1UV1UVW1T1::VertexArray }
	};

	std::unordered_map<uint64_t, std::array<int, STRIDE + 1>> OFFSET = {
		{ 0, { -1, -1, -1, -1, -1, -1, 0 }},
		{ position_flag, { 0, -1, -1, -1, -1, -1, 3 }},
		{ color_flag, { -1, 0, -1, -1, -1, -1, 4 }},
		{ position_flag | color_flag, { 0, 3, -1, -1, -1, -1, 7 }},
		{ normal_flag, { -1, -1, 0, -1, -1, -1, 3 }},
		{ position_flag | normal_flag, { 0, -1, 3, -1, -1, -1, 6 }},
		{ color_flag | normal_flag, { -1, 0, 4, -1, -1, -1, 7 }},
		{ position_flag | color_flag | normal_flag, { 0, 3, 7, -1, -1, -1, 10 }},
		{ uv_flag, { -1, -1, -1, 0, -1, -1, 2 }},
		{ position_flag | uv_flag, { 0, -1, -1, 3, -1, -1, 5 }},
		{ color_flag | uv_flag, { -1, 0, -1, 4, -1, -1, 6 }},
		{ position_flag | color_flag | uv_flag, { 0, 3, -1, 7, -1, -1, 9 }},
		{ normal_flag | uv_flag, { -1, -1, 0, 3, -1, -1, 5 }},
		{ position_flag | normal_flag | uv_flag, { 0, -1, 3, 6, -1, -1, 8 }},
		{ color_flag | normal_flag | uv_flag, { -1, 0, 4, 7, -1, -1, 9 }},
		{ position_flag | color_flag | normal_flag | uv_flag, { 0, 3, 7, 10, -1, -1, 12 }},
		{ uvw_flag, { -1, -1, -1, -1, 0, -1, 3 }},
		{ position_flag | uvw_flag, { 0, -1, -1, -1, 3, -1, 6 }},
		{ color_flag | uvw_flag, { -1, 0, -1, -1, 4, -1, 7 }},
		{ position_flag | color_flag | uvw_flag, { 0, 3, -1, -1, 7, -1, 10 }},
		{ normal_flag | uvw_flag, { -1, -1, 0, -1, 3, -1, 6 }},
		{ position_flag | normal_flag | uvw_flag, { 0, -1, 3, -1, 6, -1, 9 }},
		{ color_flag | normal_flag | uvw_flag, { -1, 0, 4, -1, 7, -1, 10 }},
		{ position_flag | color_flag | normal_flag | uvw_flag, { 0, 3, 7, -1, 10, -1, 13 }},
		{ uv_flag | uvw_flag, { -1, -1, -1, 0, 2, -1, 5 }},
		{ position_flag | uv_flag | uvw_flag, { 0, -1, -1, 3, 5, -1, 8 }},
		{ color_flag | uv_flag | uvw_flag, { -1, 0, -1, 4, 6, -1, 9 }},
		{ position_flag | color_flag | uv_flag | uvw_flag, { 0, 3, -1, 7, 9, -1, 12 }},
		{ normal_flag | uv_flag | uvw_flag, { -1, -1, 0, 3, 5, -1, 8 }},
		{ position_flag | normal_flag | uv_flag | uvw_flag, { 0, -1, 3, 6, 8, -1, 11 }},
		{ color_flag | normal_flag | uv_flag | uvw_flag, { -1, 0, 4, 7, 9, -1, 12 }},
		{ position_flag | color_flag | normal_flag | uv_flag | uvw_flag, { 0, 3, 7, 10, 12, -1, 15 }},
		{ tex_flag, { -1, -1, -1, -1, -1, 0, 1 }},
		{ position_flag | tex_flag, { 0, -1, -1, -1, -1, 3, 4 }},
		{ color_flag | tex_flag, { -1, 0, -1, -1, -1, 4, 5 }},
		{ position_flag | color_flag | tex_flag, { 0, 3, -1, -1, -1, 7, 8 }},
		{ normal_flag | tex_flag, { -1, -1, 0, -1, -1, 3, 4 }},
		{ position_flag | normal_flag | tex_flag, { 0, -1, 3, -1, -1, 6, 7 }},
		{ color_flag | normal_flag | tex_flag, { -1, 0, 4, -1, -1, 7, 8 }},
		{ position_flag | color_flag | normal_flag | tex_flag, { 0, 3, 7, -1, -1, 10, 11 }},
		{ uv_flag | tex_flag, { -1, -1, -1, 0, -1, 2, 3 }},
		{ position_flag | uv_flag | tex_flag, { 0, -1, -1, 3, -1, 5, 6 }},
		{ color_flag | uv_flag | tex_flag, { -1, 0, -1, 4, -1, 6, 7 }},
		{ position_flag | color_flag | uv_flag | tex_flag, { 0, 3, -1, 7, -1, 9, 10 }},
		{ normal_flag | uv_flag | tex_flag, { -1, -1, 0, 3, -1, 5, 6 }},
		{ position_flag | normal_flag | uv_flag | tex_flag, { 0, -1, 3, 6, -1, 8, 9 }},
		{ color_flag | normal_flag | uv_flag | tex_flag, { -1, 0, 4, 7, -1, 9, 10 }},
		{ position_flag | color_flag | normal_flag | uv_flag | tex_flag, { 0, 3, 7, 10, -1, 12, 13 }},
		{ uvw_flag | tex_flag, { -1, -1, -1, -1, 0, 3, 4 }},
		{ position_flag | uvw_flag | tex_flag, { 0, -1, -1, -1, 3, 6, 7 }},
		{ color_flag | uvw_flag | tex_flag, { -1, 0, -1, -1, 4, 7, 8 }},
		{ position_flag | color_flag | uvw_flag | tex_flag, { 0, 3, -1, -1, 7, 10, 11 }},
		{ normal_flag | uvw_flag | tex_flag, { -1, -1, 0, -1, 3, 6, 7 }},
		{ position_flag | normal_flag | uvw_flag | tex_flag, { 0, -1, 3, -1, 6, 9, 10 }},
		{ color_flag | normal_flag | uvw_flag | tex_flag, { -1, 0, 4, -1, 7, 10, 11 }},
		{ position_flag | color_flag | normal_flag | uvw_flag | tex_flag, { 0, 3, 7, -1, 10, 13, 14 }},
		{ uv_flag | uvw_flag | tex_flag, { -1, -1, -1, 0, 2, 5, 6 }},
		{ position_flag | uv_flag | uvw_flag | tex_flag, { 0, -1, -1, 3, 5, 8, 9 }},
		{ color_flag | uv_flag | uvw_flag | tex_flag, { -1, 0, -1, 4, 6, 9, 10 }},
		{ position_flag | color_flag | uv_flag | uvw_flag | tex_flag, { 0, 3, -1, 7, 9, 12, 13 }},
		{ normal_flag | uv_flag | uvw_flag | tex_flag, { -1, -1, 0, 3, 5, 8, 9 }},
		{ position_flag | normal_flag | uv_flag | uvw_flag | tex_flag, { 0, -1, 3, 6, 8, 11, 12 }},
		{ color_flag | normal_flag | uv_flag | uvw_flag | tex_flag, { -1, 0, 4, 7, 9, 12, 13 }},
		{ position_flag | color_flag | normal_flag | uv_flag | uvw_flag | tex_flag, { 0, 3, 7, 10, 12, 15, 16 }}
	};

	static std::vector<vertexarray_function> free_functions = {
		NullVertex::FreeVertexArray,
		P1::FreeVertexArray,
		C1::FreeVertexArray,
		P1C1::FreeVertexArray,
		N1::FreeVertexArray,
		P1N1::FreeVertexArray,
		C1N1::FreeVertexArray,
		P1C1N1::FreeVertexArray,
		UV1::FreeVertexArray,
		P1UV1::FreeVertexArray,
		C1UV1::FreeVertexArray,
		P1C1UV1::FreeVertexArray,
		N1UV1::FreeVertexArray,
		P1N1UV1::FreeVertexArray,
		C1N1UV1::FreeVertexArray,
		P1C1N1UV1::FreeVertexArray,
		UVW1::FreeVertexArray,
		P1UVW1::FreeVertexArray,
		C1UVW1::FreeVertexArray,
		P1C1UVW1::FreeVertexArray,
		N1UVW1::FreeVertexArray,
		P1N1UVW1::FreeVertexArray,
		C1N1UVW1::FreeVertexArray,
		P1C1N1UVW1::FreeVertexArray,
		UV1UVW1::FreeVertexArray,
		P1UV1UVW1::FreeVertexArray,
		C1UV1UVW1::FreeVertexArray,
		P1C1UV1UVW1::FreeVertexArray,
		N1UV1UVW1::FreeVertexArray,
		P1N1UV1UVW1::FreeVertexArray,
		C1N1UV1UVW1::FreeVertexArray,
		P1C1N1UV1UVW1::FreeVertexArray,
		T1::FreeVertexArray,
		P1T1::FreeVertexArray,
		C1T1::FreeVertexArray,
		P1C1T1::FreeVertexArray,
		N1T1::FreeVertexArray,
		P1N1T1::FreeVertexArray,
		C1N1T1::FreeVertexArray,
		P1C1N1T1::FreeVertexArray,
		UV1T1::FreeVertexArray,
		P1UV1T1::FreeVertexArray,
		C1UV1T1::FreeVertexArray,
		P1C1UV1T1::FreeVertexArray,
		N1UV1T1::FreeVertexArray,
		P1N1UV1T1::FreeVertexArray,
		C1N1UV1T1::FreeVertexArray,
		P1C1N1UV1T1::FreeVertexArray,
		UVW1T1::FreeVertexArray,
		P1UVW1T1::FreeVertexArray,
		C1UVW1T1::FreeVertexArray,
		P1C1UVW1T1::FreeVertexArray,
		N1UVW1T1::FreeVertexArray,
		P1N1UVW1T1::FreeVertexArray,
		C1N1UVW1T1::FreeVertexArray,
		P1C1N1UVW1T1::FreeVertexArray,
		UV1UVW1T1::FreeVertexArray,
		P1UV1UVW1T1::FreeVertexArray,
		C1UV1UVW1T1::FreeVertexArray,
		P1C1UV1UVW1T1::FreeVertexArray,
		N1UV1UVW1T1::FreeVertexArray,
		P1N1UV1UVW1T1::FreeVertexArray,
		C1N1UV1UVW1T1::FreeVertexArray,
		P1C1N1UV1UVW1T1::FreeVertexArray
	};

	void FreeVertexArray() {
		for (auto func: free_functions) {
			func();
		}
	}
}